# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 16:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0055_remove_subscription_payment'),
        ('sms', '0019_auto_20160907_1712'),
        ('payments', '0017_auto_20150521_1614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rate',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
