# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-08 16:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20160907_1712'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionrate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subscriptionrate',
            name='subscription_period',
        ),
        migrations.DeleteModel(
            name='SubscriptionPeriod',
        ),
        migrations.DeleteModel(
            name='SubscriptionRate',
        ),
    ]
