# Generated by Django 2.2.7 on 2019-11-26 10:19

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20161208_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyinstoreoffer',
            name='confirmation_message',
            field=core.fields.SMSCharField(blank=True, help_text='Response to send to a retailer when a verify-in-store voucher is valid.', max_length=160, verbose_name='confirmation message'),
        ),
        migrations.AlterField(
            model_name='verifyinstoreoffer',
            name='message',
            field=core.fields.SMSCharField(help_text="Must contain a string of X's to represent the code, length to match the specified code length.", max_length=160, verbose_name='message'),
        ),
    ]
