# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 13:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_auto_20150803_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsresponsetemplate',
            name='create_task',
            field=models.BooleanField(default=False, help_text='Incoming messages will result in a task. If not set, the response will be sent with no human involvement.', verbose_name='create task'),
        ),
    ]
