# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 16:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_auto_20160907_1426'),
    ]

    operations = [
    ]
