# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 14:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0019_auto_20160907_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokesentsms',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
