# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 12:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0021_auto_20160915_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsrecipient',
            name='page_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='smsrecipient',
            unique_together=set([('recipient', 'content_type', 'object_id', 'page_index')]),
        ),
    ]
