# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 06:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0022_auto_20160919_1308'),
    ]

    operations = [
    ]
