# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 09:15


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0023_automaticapisentsms'),
    ]

    operations = [
    ]
