# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 11:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0024_auto_20160926_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingsms',
            options={'ordering': ('at',), 'verbose_name': 'Incoming SMS'},
        ),
        migrations.RenameField(
            model_name='incomingsms',
            old_name='from_num',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='incomingsms',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.RenameField(
            model_name='incomingsms',
            old_name='to_num',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='incomingsms',
            old_name='received',
            new_name='at',
        ),
        migrations.RenameField(
            model_name='incomingsms',
            old_name='provided_id',
            new_name='gateway_id',
        ),
        migrations.AddField(
            model_name='incomingsms',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TrueAfrican'), (0, 'AfricasTalking')], default=0, verbose_name='Gateway'),
        ),
    ]
