# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 12:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0025_auto_20161101_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingsms',
            name='at',
            field=models.DateTimeField(verbose_name='At'),
        ),
        migrations.AlterField(
            model_name='incomingsms',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TrueAfrican'), (0, 'AfricasTalking')], verbose_name='Gateway'),
        ),
        migrations.AlterField(
            model_name='incomingsms',
            name='gateway_id',
            field=models.CharField(max_length=100, verbose_name='Gateway identifier'),
        ),
        migrations.AlterField(
            model_name='incomingsms',
            name='recipient',
            field=models.CharField(max_length=30, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='incomingsms',
            name='sender',
            field=models.CharField(max_length=30, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='incomingsms',
            name='text',
            field=models.TextField(blank=True, verbose_name='Message text'),
        ),
    ]
