# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-04 05:32


from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0074_auto_20170124_1724'),
        ('sms', '0026_auto_20161101_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(null=True)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('extra', jsonfield.fields.JSONField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_sms', to='customers.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
