# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-05 05:57


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0027_sentsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokesentsms',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
