# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:24


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0027_sentsms'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE sms_sentsms ALTER COLUMN extra TYPE JSONB USING extra::JSONB;"),
        migrations.RunSQL("ALTER TABLE sms_smsrecipient ALTER COLUMN extra TYPE JSONB USING extra::JSONB;"),
    ]
