# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:31


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0028_jsonfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentsms',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='smsrecipient',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
