# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:44


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0029_auto_20170406_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentsms',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
