# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0030_auto_20170407_1244'),
        ('sms', '0028_bespokesentsms_sent_by'),
    ]

    operations = [
    ]
