# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:33


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0031_merge_20170412_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokesentsms',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
