# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-02 12:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0032_auto_20170412_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsrecipient',
            name='message_failure_reason',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='smsrecipient',
            name='message_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='smsrecipient',
            name='message_status',
            field=models.CharField(db_index=True, default=b'Pending', max_length=50),
        ),
    ]
