# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-26 10:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0033_for_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingsms',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TrueAfrican'), (0, 'AfricasTalking'), (2, b'Digifarm')], verbose_name='Gateway'),
        ),
    ]
