# Generated by Django 2.2.10 on 2020-05-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0036_auto_20200129_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsresponsekeyword',
            name='keyword',
            field=models.CharField(db_index=True, help_text='This will match the whole message case-insensitively, after surrounding punctuation and whitespace has been stripped.', max_length=160, unique=True, verbose_name='keyword'),
        ),
    ]
