# Generated by Django 2.2.15 on 2020-09-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0037_auto_20200527_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsresponsetemplate',
            name='protected',
            field=models.BooleanField(default=False, help_text='Specifies whether template is protected from deletion and name changes.'),
        ),
    ]
