# Generated by Django 2.2.16 on 2020-12-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0039_populate_default_smsresponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingsms',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(0, 'AfricasTalking'), (2, 'Digifarm')], verbose_name='Gateway'),
        ),
    ]
