# Generated by Django 2.2.24 on 2021-07-15 15:06
import time
from django.db import migrations
from django.conf import settings


import logging
logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    """
    The data migration, paired with the schema migration, to
    convert BespokeSentSMS to OutgoingSMS.
    """
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sms', '0042_outgoingsms_from_bespokesentsms_schema'),
        ('tasks', '0017_outgoingsms'),
    ]

    operations = [
    ]
