# Generated by Django 2.2.24 on 2021-09-13 22:51
import time
import logging
import json
from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sms', '0044_merge_sentsms_into_outgoingsms'),
    ]

    operations = [
    ]

