# Generated by Django 2.2.24 on 2021-07-15 15:06
import json
import time

from datetime import datetime
from django.db import migrations
from django.conf import settings


import logging


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('markets', '0031_auto_20191126_1319'),
        ('sms', '0045_merge_automatedsmsresponse_into_outgoingsms'),
        ('weather', '0014_remove_forecastday_json'),
    ]

    operations = [
    ]
