# Generated by Django 2.2.24 on 2021-07-15 15:06
import json
import hashlib
import time

from datetime import datetime
from django.db import migrations
from django.conf import settings
from psycopg2.extras import DateRange


import logging


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0024_commodity_season_length_days'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('markets', '0031_auto_20191126_1319'),
        ('payments', '0020_auto_20191126_1319'),
        ('sms', '0046_merge_weather_forecasts_into_outgoingsms'),
    ]

    operations = [
    ]
