# Generated by Django 2.2.24 on 2021-10-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0047_merge_remaining_message_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsrecipient',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='smsrecipient',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='smsrecipient',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sms.OutgoingSMS'),
        ),
        migrations.DeleteModel(
            name='SentSMS',
        ),
    ]
