# Generated by Django 2.2.24 on 2021-11-12 17:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.db.models.indexes import Index


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0048_delete_unused_sms_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOutgoingSMSSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('message_type', models.CharField(choices=[('?', 'Unknown'), ('bulk', 'Bulk'), ('one', 'Individual'), ('task', 'Task_Response'), ('auto', 'Template_Response'), ('new', 'New_Customer_Response'), ('tip', 'Agri_Tip'), ('wxke', 'Weather_Kenmet'), ('wxpv', 'Weather_Plantvillage'), ('mkt', 'Market_Price'), ('sub', 'Subscription_Notification'), ('vchr', 'Voucher'), ('wxmkt', 'Weather_And_Market')], default='?', max_length=8)),
                ('count', models.PositiveIntegerField()),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Daily OutgoingSMS Summary',
                'verbose_name_plural': 'Daily OutgoingSMS Summaries'
            },
        ),
        migrations.AddIndex('DailyOutgoingSMSSummary', Index(fields=['date'], name='date_index')),
        migrations.AddConstraint(
            model_name='DailyOutgoingSMSSummary',
            constraint=models.UniqueConstraint(fields=('date', 'message_type'), name='unique_date_message_type'),
        ),
    ]
