# Generated by Django 3.2.13 on 2022-06-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_remove_world_county_data'),
        ('sms', '0055_add_empty_message_smsresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsresponsetemplate',
            name='all_countries',
            field=models.BooleanField(default=True,
                                      help_text='This template is used for incoming SMS messages from any country.',
                                      verbose_name='all countries'),
        ),
        migrations.AddField(
            model_name='smsresponsetemplate',
            name='countries',
            field=models.ManyToManyField(blank=True,
                                         help_text='The countries that this template responds to.',
                                         limit_choices_to={'level': 0}, to='world.Border'),
        ),
        migrations.AddField(
            model_name='smsresponsetemplate',
            name='keywords',
            field=models.ManyToManyField(related_name='responses', to='sms.SMSResponseKeyword'),
        ),
        migrations.AddField(
            model_name='smsresponsetemplate',
            name='action',
            field=models.CharField(choices=[('none', 'No Action'), ('task', 'Create Task'), ('join', 'Join Customer'),
                                            ('stop', 'Stop Customer')], default='none',
                                   help_text='The action to take when this messages is received. E.g. create a task, or join or stop the customer. If no action is specified, the text in this template will be automatically sent with no staff involvement.',
                                   max_length=20, verbose_name='action'),
        ),
    ]
