# Generated by Django 3.2.13 on 2022-06-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0057_convert_responsetemplate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsresponsekeyword',
            name='response',
        ),
        migrations.RemoveField(
            model_name='smsresponsetemplate',
            name='create_task',
        ),
    ]
