# Generated by Django 3.2.16 on 2022-12-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0060_add_nps_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSResponseText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[(None, '(Unknown)'), ('bnt', 'Bantu'), ('bem', 'Bemba'), ('eng', 'English'), ('swa', 'Kiswahili'), ('loz', 'Lozi'), ('lug', 'Luganda'), ('nya', 'Nyanja'), ('toi', 'Tonga')], default='eng', max_length=3, verbose_name='language')),
                ('text', models.TextField(help_text='Valid placeholder values are: call_centre, shortcode, till_number, year_price, month_price. Write as {call_centre}', verbose_name='text')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sms.smsresponsetemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
