# Generated by Django 3.2.16 on 2022-12-01 18:04

from django.db import migrations


def convert_data(apps, schema_editor):
    """
        Converts:
           - SMSResponseTemplate.text to a new SMSResponseText ForeignKey record with 'eng' as the language
    """
    SMSResponseTemplate = apps.get_model('sms', 'SMSResponseTemplate')
    SMSResponseText = apps.get_model('sms', 'SMSResponseText')

    new_objs = []
    for template in SMSResponseTemplate.objects.all():
        text = template.text
        new_objs.append(
            SMSResponseText(
                language="eng",  # All templates were English initially
                text=text,
                template=template,
            )
        )

    if new_objs:
        SMSResponseText.objects.bulk_create(new_objs)


def reverse_data(apps, schema_editor):
    """
        Reverses:
           - SMSResponseText records to their corresponding SMSResponseTemplate.text field
    """
    SMSResponseTemplate = apps.get_model('sms', 'SMSResponseTemplate')
    SMSResponseText = apps.get_model('sms', 'SMSResponseText')

    for smsr_text in SMSResponseText.objects.all():
        smsr_template = smsr_text.template
        smsr_template.text = smsr_text.text
        smsr_template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0061_smsresponsetext'),
    ]

    operations = [
        migrations.RunPython(convert_data, reverse_code=reverse_data),
    ]
