# Generated by Django 3.2.16 on 2022-12-01 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0062_smsresponsetext_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsresponsetemplate',
            name='text',
        ),
    ]
