# Generated by Django 3.2.16 on 2022-12-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0063_remove_smsresponsetemplate_text'),
    ]

    operations = [
        migrations.RenameModel('SMSResponseText', 'SMSResponseTranslation'),
        migrations.AlterField(
            model_name='smsresponsetranslation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sms.smsresponsetemplate'),
        ),
    ]
