# Generated by Django 4.1.9 on 2023-10-25 11:40

from django.db import migrations

from sms.constants import Actions
from core.constants import LANGUAGES


def create_df_sync_sms_templates(apps, schema_editor):
    SMSResponseTemplate = apps.get_model('sms', 'SMSResponseTemplate')
    SMSResponseTranslation = apps.get_model('sms', 'SMSResponseTranslation')
    template, created = SMSResponseTemplate.objects.get_or_create(
        action=Actions.JOIN, name='digifarm_sync', protected=True
    )
    SMSResponseTranslation.objects.get_or_create(
        template=template, language=LANGUAGES.ENGLISH,
        defaults={
            "text": "Hello {firstName} {lastName}. Welcome to Digifarm weather and agronomy advisory services powered by iShamba"
        }
    )
    SMSResponseTranslation.objects.get_or_create(
        template=template, language=LANGUAGES.KISWAHILI,
        defaults={
            "text": "Jambo {firstName} {lastName}. Karibu kwenye huduma ya mawaidha ya ukulima ya Digifarm ikiwezeshwa na iShamba"
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0064_alter_smsresponsetranslation_template'),
    ]

    operations = [
        migrations.RunPython(create_df_sync_sms_templates)
    ]
