# Generated by Django 4.1.10 on 2023-11-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0065_digifarm_sync_sms_templates'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='outgoingsms',
            index=models.Index(fields=['text'], name='outgoingsms_text_idx'),
        ),
    ]
