# Generated by Django 4.1.9 on 2024-03-28 16:34

from django.db import migrations, models
import search.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0066_outgoingsms_outgoingsms_text_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingsms',
            name='gateway',
            field=models.PositiveSmallIntegerField(choices=[(0, 'AfricasTalking'), (1, 'Digifarm')], verbose_name='Gateway'),
        ),
        migrations.AlterField(
            model_name='incomingsms',
            name='text',
            field=search.fields.ESAnalyzedTextField(analyzer='english', blank=True, verbose_name='Message text'),
        ),
    ]
