# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 07:45


from django.db import migrations
from markets.models import generate_mpm_hash


def gen_hashes(apps, schema_editor):
    MarketPriceMessage = apps.get_model('markets', 'MarketPriceMessage')
    for mpm in MarketPriceMessage.objects.only('hash').iterator():
        mpm.hash = generate_mpm_hash()
        mpm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0022_marketpricemessage_hash'),
    ]

    operations = [
        migrations.RunPython(gen_hashes,
                             reverse_code=migrations.RunPython.noop),
    ]
