# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 07:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0023_populate_hash_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketpricemessage',
            name='hash',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
