# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 08:25
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations, models, transaction
from django.db.utils import IntegrityError


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0024_remove_hash_null'),
        ('sms', '0019_auto_20160907_1712'),
    ]

    operations = [
    ]
