# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 10:14


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0025_auto_20160909_0925'),
    ]

    operations = [
    ]
