# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 11:03


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0027_auto_20160909_1124'),
    ]

    operations = [
    ]
