# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 15:56


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0029_auto_20160914_1544'),
    ]

    operations = [
    ]
