# Generated by Django 2.2.7 on 2019-11-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0030_auto_20161102_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='is_main_market',
            field=models.BooleanField(default=False, help_text='Are price updates are reliably regularly received?'),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='The number of [unit]s that this price is for.', verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='date',
            field=models.DateField(help_text='The date this price was retrieved at the market.', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='price',
            field=models.PositiveSmallIntegerField(help_text='In Kenyan shillings.', verbose_name='price'),
        ),
    ]
