# Generated by Django 2.2.24 on 2021-10-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0031_auto_20191126_1319'),
    ]

    operations = [
    ]
