# Generated by Django 4.1.6 on 2023-02-14 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0117_remove_customermarketsubscription"),
        ("markets", "0034_marketsubscription_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketsubscription",
            name="backup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backup_subscriptions",
                to="markets.market",
            ),
        ),
        migrations.AlterField(
            model_name="marketsubscription",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_subscriptions",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="marketsubscription",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_subscriptions",
                to="markets.market",
            ),
        ),
    ]
