# Generated by Django 4.1.7 on 2023-03-11 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agri", "0025_delete_agritipsentsms"),
        ("customers", "0118_alter_customercategory_sorting"),
        ("markets", "0035_alter_marketsubscription_backup_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marketsubscription",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="marketsubscription",
            name="commodity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_subscriptions",
                to="agri.commodity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketsubscription",
            unique_together={("customer", "market", "commodity")},
        ),
    ]
