# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:53


from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160128_1108'),
    ]

    operations = [
    ]
