# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:56


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scheduledjob_uuid'),
    ]

    operations = [
    ]
