# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:56


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160329_1756'),
    ]

    operations = [
    ]
