# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 16:48


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160329_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledJob',
        ),
    ]
