# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
