# Generated by Django 4.1.4 on 2022-12-29 18:35

from django.db import migrations


def convert_data(apps, schema_editor):
    """
        Creates a Domain for each existing Client.
        Moves the Client.domain_url to Domain.domain.
        Sets Domain.tenant = Client
        Sets Domain.is_primary if Client is iShamba
    """
    Client = apps.get_model('core', 'Client')
    Domain = apps.get_model('core', 'Domain')

    for client in Client.objects.all():
        Domain.objects.create(
            domain=client.domain_url,
            is_primary=(client.name.lower() == 'ishamba'),
            tenant=client,
        )


def reverse_data(apps, schema_editor):
    """
        Reverses the migration
    """
    Client = apps.get_model('core', 'Client')
    Domain = apps.get_model('core', 'Domain')

    for domain in Domain.objects.all():
        client = domain.tenant
        client.domain_url = domain.domain
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_move_to_django_tenants_add_domain_class'),
    ]

    operations = [
        migrations.RunPython(convert_data, reverse_code=reverse_data),
    ]
