# Generated by Django 4.1.4 on 2022-12-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_django_tenants_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='domain_url',
        ),
    ]
