# Generated by Django 4.1.9 on 2023-09-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_client_accept_only_registered_calls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='accept_only_registered_calls',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='at_api_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='at_sender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='at_username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='pusher_app_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='pusher_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='pusher_secret',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='send_weather',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='sms_shortcode',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='tip_reports_to',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='voice_dequeue_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='voice_queue_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
