# Generated by Django 4.1.13 on 2024-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_client_accept_only_registered_calls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tips_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
