# Generated by Django 4.1.9 on 2023-09-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenters', '0001_initial'),
        ('calls', '0016_auto_20191126_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='callcenters.callcenter'),
        ),
    ]
