from decouple import config

# outgoing integration
DIGIFARM_USERNAME = config('DIGIFARM_USERNAME')
DIGIFARM_PASSWORD = config('DIGIFARM_PASSWORD')
DIGIFARM_SMS_GATEWAY_URL = config('DIGIFARM_SMS_GATEWAY_URL')

# incoming integration
DIGIFARM_AUTHENTICATION_SECRET = config('DIGIFARM_AUTHENTICATION_SECRET')

# Feature Flag
ENABLE_DIGIFARM_INTEGRATION = config('ENABLE_DIGIFARM_INTEGRATION', False, cast=bool)
