# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-02 10:47


from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0005_auto_20161020_1029'),
        ('customers', '0074_auto_20170124_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('send_after', models.DurationField(help_text='The time after the series starts that this tip is sent', verbose_name='Send after')),
                ('text', models.TextField(verbose_name='Tip content')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='world.County')),
            ],
            options={
                'ordering': ['-send_after'],
            },
        ),
        migrations.CreateModel(
            name='TipSentSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(null=True)),
                ('time_sent', models.DateTimeField(null=True)),
                ('tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tips.Tip')),
            ],
            options={
                'ordering': ('-time_sent',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('start_event', models.CharField(blank=True, help_text='The event which tips are sent in relation to, e.g.,"calf due date". Leave blank if there is no event.', max_length=255, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Tip Series',
            },
        ),
        migrations.CreateModel(
            name='TipSeriesSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('start', models.DateTimeField(default=django.utils.timezone.now, help_text='Set to the time of the event the tips are based on.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.TipSeries')),
                ('ended', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tip',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.TipSeries'),
        ),
    ]
