# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-02 12:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-delay_signed']},
        ),
        migrations.RemoveField(
            model_name='tip',
            name='send_after',
        ),
        migrations.AddField(
            model_name='tip',
            name='delay',
            field=models.DurationField(default='00:05:00', help_text='The time after the series starts that this tip is sent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='delay_before',
            field=models.BooleanField(default=False, help_text='Convert delay to be the time before the series starts'),
        ),
        migrations.AddField(
            model_name='tip',
            name='delay_signed',
            field=models.DurationField(default='00:05:00', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipseries',
            name='start_event',
            field=models.CharField(blank=True, help_text='The event which tips are sent in relation to, e.g.,calf due date or start of the year', max_length=255, null=True),
        ),
    ]
