# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-02 13:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20170302_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='delay_signed',
            field=models.DurationField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='tipseriessubscription',
            name='start',
            field=models.DateTimeField(help_text='Set to the time of the event that the tip series is based on.'),
        ),
    ]
