# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-04 05:32


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_create_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipsentsms',
            name='tip',
        ),
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['delay_signed']},
        ),
        migrations.AlterField(
            model_name='tip',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='tips.TipSeries'),
        ),
        migrations.AlterField(
            model_name='tipseriessubscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_series', to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='tipseriessubscription',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tips.TipSeries'),
        ),
        migrations.DeleteModel(
            name='TipSentSMS',
        ),
        migrations.AddField(
            model_name='tipsent',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.TipSeriesSubscription'),
        ),
        migrations.AddField(
            model_name='tipsent',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.Tip'),
        ),
        migrations.AlterUniqueTogether(
            name='tipsent',
            unique_together=set([('tip', 'subscription')]),
        ),
    ]
