# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-07 16:47


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_auto_20170304_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipsent',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_sent', to='tips.TipSeriesSubscription'),
        ),
    ]
