# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-08 17:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_auto_20170307_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipseries',
            name='end_message',
            field=models.TextField(blank=True, default='', help_text='Message sent to customer when tip series finishes'),
        ),
    ]
