# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-08 17:01


from django.db import migrations
from django.conf import settings


def create_end_messages(apps, schema_editor):
    TipSeries = apps.get_model('tips', 'TipSeries')
    msg = "Hello, You have come to the end of the {name} tips. Send us the name of a new crop or livestock you would now like to receive tips on to {shortcode}."
    for series in TipSeries.objects.only('pk', 'name').all():
        series.end_message = msg.format(name=series.name.strip(), shortcode='21606')
        series.save(update_fields=['end_message'])


def cleanup_end_messages(apps, schema_editor):
    TipSeries = apps.get_model('tips', 'TipSeries')
    TipSeries.objects.all().update(end_message='')


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0008_tipseries_end_message'),
    ]

    operations = [
        migrations.RunPython(create_end_messages, cleanup_end_messages)
    ]
