# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-15 13:00


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0009_add_end_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipsent',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='tips.Tip'),
        ),
    ]
