# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-16 09:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0010_auto_20170315_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipseries',
            name='start_event',
            field=models.CharField(blank=True, default='', help_text='The event which tips are sent in relation to, e.g.,calf due date or start of the year', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipseriessubscription',
            name='ended',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
