# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-17 16:34


from django.db import migrations
from django.db.models import Q


def deactivate_subscriptions(apps, schema_editor):
    TipSeriesSubscription = apps.get_model('tips', 'TipSeriesSubscription')

    (TipSeriesSubscription.objects.filter(Q(customer__has_requested_stop=True) |
                                         Q(customer__is_registered=False) |
                                         Q(customer__categories__name__iexact='suspend service'))
                                  .update(ended=True))


def reactivate_subscriptions(apps, schema_editor):
    TipSeriesSubscription = apps.get_model('tips', 'TipSeriesSubscription')

    (TipSeriesSubscription.objects.filter(Q(customer__has_requested_stop=True) |
                                         Q(customer__is_registered=False) |
                                         Q(customer__categories__name__iexact='suspend service'))
                                  .update(ended=False))


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0011_auto_20170316_1202'),
    ]

    operations = [
        migrations.RunPython(deactivate_subscriptions, reactivate_subscriptions)
    ]
