# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-29 18:58


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0012_end-inactive-subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipseriessubscription',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tips.TipSeries', verbose_name='Tip series'),
        ),
        migrations.AlterField(
            model_name='tipseriessubscription',
            name='start',
            field=models.DateTimeField(help_text='This is the event that the tip series is based on'),
        ),
    ]
