# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-30 19:12


from django.db import migrations


def remove_sent_tips_false_subscriptions(apps, schema_editor):
    TipSeriesSubscription = apps.get_model('tips', 'TipSeriesSubscription')
    CommoditySubscription = apps.get_model('customers', 'CommoditySubscription')

    # Find original subscriptions with send_agri_tips=False
    send_false = (CommoditySubscription.objects.exclude(ended=True)
                                       .filter(send_agri_tips=False))
    # Look for the tip subscriptions that were created
    for sub in send_false.iterator():
        if sub.commodity.variant_of:
            name = sub.commodity.variant_of.name
        else:
            name = sub.commodity.name
        try:
            tip_sub = TipSeriesSubscription.objects.get(series__name=name, customer=sub.subscriber)
            # Delete them
            tip_sub.delete()
        except TipSeriesSubscription.DoesNotExist:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0013_auto_20170329_2158'),
    ]

    operations = [
        migrations.RunPython(remove_sent_tips_false_subscriptions, migrations.RunPython.noop)
    ]
