# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:25


from django.db import migrations


def add_series_start_event(apps, schema_editor):
    TipSeries = apps.get_model('tips', 'TipSeries')
    missing_start_event = TipSeries.objects.filter(start_event='')
    missing_start_event.update(start_event="Start of the year")


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0015_add_new_subs'),
    ]

    operations = [
        migrations.RunPython(add_series_start_event, migrations.RunPython.noop)
    ]
