# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 16:02


from django.db import migrations


def add_nairobi_tips(apps, schema_editor):
    Tip = apps.get_model('tips', 'Tip')

    similar_tips = Tip.objects.filter(county_id=13) # Kiambu - Central Region
    new_tips = []

    for t in similar_tips.iterator():
        t.pk = None
        t.county_id = 34
        new_tips.append(t)

    Tip.objects.bulk_create(new_tips)


def remove_nairobi_tips(apps, schema_editor):
    Tip = apps.get_model('tips', 'Tip')
    Tip.objects.filter(county_id=34).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0016_adjust_series_start_desc'),
    ]

    operations = [
        migrations.RunPython(add_nairobi_tips, remove_nairobi_tips)
    ]
