# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 15:43


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0017_add_nairobi_tips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipsent',
            options={'ordering': ('-created',)},
        ),
    ]
