# Generated by Django 2.2.24 on 2021-12-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0020_map_county_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='county',
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='new_county',
            new_name='county',
        ),
    ]
