# Generated by Django 3.2.16 on 2022-12-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0021_remove_old_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='county',
            new_name='border1',
        ),
    ]
