# Generated by Django 3.2.16 on 2022-12-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0022_rename_county_tip_border1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[(None, '(Unknown)'), ('bnt', 'Bantu'), ('bem', 'Bemba'), ('eng', 'English'), ('swa', 'Kiswahili'), ('loz', 'Lozi'), ('lug', 'Luganda'), ('nya', 'Nyanja'), ('toi', 'Tonga')], default='eng', max_length=3, verbose_name='language')),
                ('text', models.TextField(verbose_name='Tip content')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tips.tip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
