# Generated by Django 3.2.16 on 2022-12-01 18:04

from django.db import migrations


def convert_data(apps, schema_editor):
    """
        Converts:
           - Tip.text to a new TipTranslation ForeignKey record with 'eng' as the language
    """
    Tip = apps.get_model('tips', 'Tip')
    TipTranslation = apps.get_model('tips', 'TipTranslation')

    new_objs = []
    for tip in Tip.objects.all():
        text = tip.text
        new_objs.append(
            TipTranslation(
                language="eng",  # All templates were English initially
                text=text,
                tip=tip,
            )
        )

    if new_objs:
        TipTranslation.objects.bulk_create(new_objs)


def reverse_data(apps, schema_editor):
    """
        Reverses:
           - TipTranslation records to their corresponding Tip.text field
    """
    Tip = apps.get_model('tips', 'Tip')
    TipTranslation = apps.get_model('tips', 'TipTranslation')

    for tip_text in TipTranslation.objects.all():
        # Warning: If there are multiple translations for a tip, each will get overwritten by others.
        tip = tip_text.tip
        tip.text = tip_text.text
        tip.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0023_tiptranslation'),
    ]

    operations = [
        migrations.RunPython(convert_data, reverse_code=reverse_data),
    ]
