# Generated by Django 4.1.6 on 2023-02-17 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0117_remove_customermarketsubscription"),
        ("tips", "0025_remove_tip_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipseriessubscription",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tip_subscriptions",
                to="customers.customer",
            ),
        ),
    ]
