# Generated by Django 4.1.9 on 2024-03-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0029_populate_customer_commodities_from_tipseries'),
        ('sms', '0067_alter_incomingsms_gateway_alter_incomingsms_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('customer_filters', models.JSONField(blank=True, null=True)),
                ('season_length_override', models.PositiveIntegerField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_seasons', to='tips.tipseries')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tipseries',
            name='legacy',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TipMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tip_message', to='sms.outgoingsms')),
                ('tip_translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_messages', to='tips.tiptranslation')),
                ('tip_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_messages', to='tips.tipseason')),
            ],
            options={
                'unique_together': {('tip_translation', 'tip_season')},
            },
        ),
    ]
