# Generated by Django 4.1.9 on 2024-04-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0025_delete_agritipsentsms'),
        ('tips', '0030_tipseason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='agri.commodity'),
        ),
        migrations.AddField(
            model_name='tipseason',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tip_seasons', to='agri.commodity'),
        ),
        migrations.AddField(
            model_name='tip',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
