# Generated by Django 4.1.9 on 2024-04-16 15:08

from django.db import migrations


def populate_tips_and_seasons_commodity_fk(apps, schema_editor):
    TipSeries = apps.get_model('tips', 'tipseries')
    for tip_series in TipSeries.objects.all():
        tip_series.tips.all().update(commodity_id=tip_series.commodity_id, legacy=tip_series.legacy)
        tip_series.tip_seasons.all().update(commodity_id=tip_series.commodity_id)


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0031_tip_commodity_tipseason_commodity'),
    ]

    operations = [
        migrations.RunPython(populate_tips_and_seasons_commodity_fk, migrations.RunPython.noop)
    ]
