# Generated by Django 4.1.9 on 2024-04-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0025_delete_agritipsentsms'),
        ('tips', '0032_tips_and_seasons_commodity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='series',
        ),
        migrations.RemoveField(
            model_name='tipseason',
            name='series',
        ),
        migrations.AlterField(
            model_name='tip',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='agri.commodity'),
        ),
        migrations.AlterField(
            model_name='tipseason',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_seasons', to='agri.commodity'),
        ),
    ]
