# Generated by Django 4.1.9 on 2024-04-16 16:18

from django.db import migrations
from django.db.models import F


def cleanup_tips_delay_field(apps, schema_editor):
    Tip = apps.get_model('tips', 'tip')
    Tip.objects.filter(legacy=True).update(delay=F('delay_signed'))


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0033_remove_tip_series_remove_tipseason_series_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_tips_delay_field, migrations.RunPython.noop)
    ]
