# Generated by Django 4.1.9 on 2024-04-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0034_tips_delay_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['delay']},
        ),
        migrations.RemoveField(
            model_name='tip',
            name='delay_before',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='delay_signed',
        ),
    ]
