# Generated by Django 4.1.13 on 2024-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenters', '0004_callcentersender_remove_callcenter_sender_id_and_more'),
        ('tips', '0035_alter_tip_options_remove_tip_delay_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='call_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='tips', to='callcenters.callcenter'),
        ),
    ]
