# Generated by Django 4.1.13 on 2024-04-30 07:22

from django.db import migrations


def backfill_tips_callcenter(apps, schema_editor):
    TipModel = apps.get_model('tips', 'tip')
    CallCenter = apps.get_model('callcenters', 'callcenter')
    Border = apps.get_model('world', 'border')

    kenya = Border.objects.get(name='Kenya')
    call_center = CallCenter.objects.get(border=kenya)
    TipModel.objects.all().update(call_center=call_center)


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0036_tip_call_centers'),
        ('callcenters', '0004_callcentersender_remove_callcenter_sender_id_and_more'),
        ('world', '0012_auto_20231130_2259'),
    ]

    operations = [
        migrations.RunPython(backfill_tips_callcenter, migrations.RunPython.noop)
    ]
