# Generated by Django 4.1.13 on 2024-05-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenters', '0004_callcentersender_remove_callcenter_sender_id_and_more'),
        ('tips', '0037_auto_20240430_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='call_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='callcenters.callcenter'),
        ),
    ]
