# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 11:45


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0019_auto_20150608_1218'),
    ]

    operations = [
    ]
