# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 13:26


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0020_auto_20160322_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agritipsms',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri.Commodity', verbose_name='Commodity'),
        ),
        migrations.AlterField(
            model_name='agritipsms',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_type',
            field=models.CharField(choices=[(b'crop', b'Crop'), (b'livestock', b'Livestock')], default=b'crop', max_length=10, verbose_name='Commodity type'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='epoch_description',
            field=models.CharField(blank=True, help_text='The event from which other dates are measured, e.g. "calf due-date". Leave blank for seasonal commodities.', max_length=255, null=True, verbose_name='Epoch description'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='short_name',
            field=models.CharField(max_length=14, unique=True, verbose_name='Short name'),
        ),
    ]
