# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 14:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0021_auto_20160907_1426'),
    ]

    operations = [
    ]
