# Generated by Django 2.2.7 on 2019-11-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0022_auto_20160914_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agritipsms',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agri.Region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_type',
            field=models.CharField(choices=[('crop', 'Crop'), ('livestock', 'Livestock')], default='crop', max_length=10, verbose_name='Commodity type'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='fallback_commodity',
            field=models.ForeignKey(blank=True, help_text='For event-based agri-tip streams only: the commodity that will supply tips when this stream ends.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agri.Commodity'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='gets_market_prices',
            field=models.BooleanField(default=False, help_text='Market prices are regularly received for this commodity.', verbose_name='Gets market prices'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='variant_of',
            field=models.ForeignKey(blank=True, help_text='The commodity-stream from which the customer will be sent SMS tips. Leave blank if this commodity has its own agri-tip stream.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='agri.Commodity'),
        ),
    ]
