# Generated by Django 2.2.17 on 2021-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0023_auto_20191126_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='season_length_days',
            field=models.IntegerField(blank=True, default=None, help_text='The max length of a typical growing season. Leave blank for livestock and perennials.', null=True),
        ),
    ]
