# Generated by Django 2.2.24 on 2021-10-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0024_commodity_season_length_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgriTipSentSMS',
        ),
    ]
