# Generated by Django 4.1.13 on 2024-05-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0025_delete_agritipsentsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='tips_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
