# Generated by Django 4.1.12 on 2023-10-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interrogation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interrogationsession",
            name="session_type",
            field=models.IntegerField(default=0),
        ),
    ]
