export const products = [
    {
        name : "Apple iMac 27-inch",
        category: 'PC',
        brand: 'Apple',
        description: 'Apple iMac 27-inch with Retina 5K display',
        price : 2999,
    },
    {
        name : "Apple MacBook Pro 13-inch",
        category: 'Laptop',
        brand: 'Apple',
        description: 'Apple MacBook Pro 13-inch with M1 chip',
        price : 1299,
    },
    {
        name : "Apple iPad Pro 12.9-inch",
        category: 'Tablet',
        brand: 'Apple',
        description: 'Apple iPad Pro 12.9-inch with M1 chip',
        price : 1099,
    },
    {
        name : "Apple iPhone 12 Pro Max",
        category: 'Smartphone',
        brand: 'Apple',
        description: 'Apple iPhone 12 Pro Max with 5G',
        price : 1099,
    },
    {
        name : "Apple Watch Series 6",
        category: 'Smartwatch',
        brand: 'Apple',
        description: 'Apple Watch Series 6 with GPS',
        price : 399,
    },
    {
        name : "Apple AirPods Pro",
        category: 'Headphone',
        brand: 'Apple',
        description: 'Apple AirPods Pro with Active Noise Cancellation',
        price : 249,
    },
    {
        name : "Apple HomePod mini",
        category: 'Speaker',
        brand: 'Apple',
        description: 'Apple HomePod mini with Siri',
        price : 99,
    },
    {
        name : "Apple TV 4K",
        category: 'TV',
        brand: 'Apple',
        description: 'Apple TV 4K with Dolby Vision',
        price : 179,
    },
    {
        name : "Apple AirTag",
        category: 'Tracker',
        brand: 'Apple',
        description: 'Apple AirTag with Precision Finding',
        price : 29,
    },
    {
        name : "Apple MagSafe Charger",
        category: 'Charger',
        brand: 'Apple',
        description: 'Apple MagSafe Charger for iPhone 12',
        price : 39,
    },
    {
        name : "Apple USB-C Power Adapter",
        category: 'Adapter',
        brand: 'Apple',
        description: 'Apple USB-C Power Adapter for MacBook Pro',
        price : 69,
    },
    {
        name : "Apple USB-C to Lightning Cable",
        category: 'Cable',
        brand: 'Apple',
        description: 'Apple USB-C to Lightning Cable for iPhone',
        price : 19,
    },  
]