# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 11:41


from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Failed'), (1, 'Queued'), (2, 'Started'), (3, 'Complete')], default=1, verbose_name='Status')),
                ('exported_file', models.FilePathField(blank=True, match='.csv$', max_length=256, path='/usr/local/django/portal.ishamba.com/media/exports')),
                ('map_file', models.FilePathField(blank=True, match='.png$', max_length=256, path='/usr/local/django/portal.ishamba.com/media/exports')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='Export type')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
