# Generated by Django 2.2.7 on 2019-12-02 08:28

from django.db import migrations, models
import exports.models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapexport',
            name='exported_file',
            field=models.FilePathField(blank=True, match='.csv$', max_length=256, path=exports.models.media_root_fn),
        ),
        migrations.AlterField(
            model_name='mapexport',
            name='map_file',
            field=models.FilePathField(blank=True, match='.png$', max_length=256, path=exports.models.media_root_fn),
        ),
    ]
