# Generated by Django 3.2.10 on 2021-12-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='export',
            name='filters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='mapexport',
            name='fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='mapexport',
            name='filters',
            field=models.JSONField(default=dict),
        ),
    ]
