# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 09:05


import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20150121_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('boundary', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
            ],
        ),
    ]
