# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 09:05


from django.db import migrations


from ..utils import process_counties_kml


def add_counties(apps, schema_editor):
    pass


def remove_counties(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_county'),
    ]

    operations = [
        migrations.RunPython(add_counties, remove_counties)
    ]
