# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 09:29


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_add_counties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name']},
        ),
    ]
