# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-04 05:32


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20161020_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name'], 'verbose_name_plural': 'Counties'},
        ),
    ]
