# Generated by Django 2.2.7 on 2019-11-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_auto_20170304_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='fips',
            field=models.CharField(max_length=2, verbose_name='FIPS Code', null=True),  # Imported data set has a null value for Pakistan
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso2',
            field=models.CharField(max_length=2, verbose_name='2 Digit ISO'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso3',
            field=models.CharField(max_length=3, verbose_name='3 Digit ISO'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='pop2005',
            field=models.IntegerField(verbose_name='Population 2005'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='region',
            field=models.IntegerField(verbose_name='Region Code'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='subregion',
            field=models.IntegerField(verbose_name='Sub-Region Code'),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='un',
            field=models.IntegerField(verbose_name='United Nations Code'),
        ),
    ]
