# Generated by Django 2.2.24 on 2021-12-04 16:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.db.models.indexes import Index


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_auto_20191126_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=120)),
                ('level', models.SmallIntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='subdivisions', to='world.border')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('name_en', models.CharField(max_length=120)),
                ('border', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Borders',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex('Border', Index(fields=['country'], name='border_country_idx')),
        migrations.AddIndex('Border', Index(fields=['level'], name='border_level_idx')),
        migrations.AddIndex('Border', Index(fields=['name'], name='border_name_idx')),
        migrations.AddIndex('Border', Index(fields=['name_en'], name='border_name_en_idx')),
        migrations.CreateModel(
            name='BorderLevelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.SmallIntegerField(blank=True, null=True)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('level', models.SmallIntegerField()),
                ('country', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('name_en', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Border level names',
            },
        ),
    ]
