# Generated by Django 2.2.24 on 2021-12-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0104_remove_old_location_fields'),
        ('tips', '0021_remove_old_county'),
        ('weather', '0018_remove_old_county'),
        ('world', '0009_populate_borders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
        # Deleting the County model causes older migration problems on a fresh database.
        # To instead, we raise an ImproperlyConfigured exception on use, and delete the
        # data from the table.
        # migrations.DeleteModel(
        #     name='County',
        # ),
    ]
