# Generated by Django 4.1.9 on 2023-11-30 19:59

from django.db import migrations


def correct_kamahuha_ward_name(apps, schema_editor):
    Border = apps.get_model('world', 'border')

    Border.objects.filter(country='Kenya', level=3, name='Kamahuhu').update(name='Kamahuha')


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_remove_world_county_data'),
    ]

    operations = [
        migrations.RunPython(correct_kamahuha_ward_name)
    ]
