# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 14:36


import json
import os

from django.conf import settings
from django.db import migrations


MAPPING = {
    'f': ['F', 'FEMALE', 'FF'],
    'm': ['M', 'M.', 'MALE', 'MALW', 'MM', 'male'],
    '': ['FM', 'G', 'J', 'MF', 'N', 'am', 'c', '-'],
}
OLD_DATA_NAME = 'customers/migrations/fixtures/0047_old_gender_data.json'
OLD_DATA_PATH = os.path.join(settings.PROJECT_ROOT, OLD_DATA_NAME)


def fix_genders(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    customers = (Customer.objects.only('pk', 'sex')
                         .exclude(sex__in=MAPPING.keys()))

    unpacked = {i: k for k, v in MAPPING.items() for i in v}

    for customer in customers.iterator():
        new_value = unpacked.get(customer.sex, '')
        customer.sex = new_value
        customer.save()


def unfix_genders(apps, schema_editor):
    with open(OLD_DATA_PATH, 'r') as fh:
        old_data = json.load(fh)

    Customer = apps.get_model('customers', 'Customer')
    customers = Customer.objects.only('pk').filter(pk__in=old_data.keys())

    for customer in customers.iterator():
        customer.sex = old_data[str(customer.pk)]
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0046_auto_20160202_0854'),
    ]

    operations = [
        migrations.RunPython(fix_genders, unfix_genders)
    ]
