# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-19 10:58


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0021_auto_20160126_1612'),
        ('customers', '0046_auto_20160202_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMarketSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_subscriptions', to='markets.Market')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_subscriptions', to='markets.Market')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='markets',
            field=models.ManyToManyField(through='customers.CustomerMarketSubscription', to='markets.Market'),
        ),
    ]
