# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 13:09


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0048_fix_broken_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermarketsubscription',
            name='backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_subscriptions', to='markets.Market'),
        ),
    ]
