# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 15:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0049_auto_20160720_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customermarketsubscription',
            unique_together=set([('customer', 'market')]),
        ),
    ]
