# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 12:11


from django.db import migrations

from core.utils.functional import grouper


def move_to_m2m(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    CustomerMarketSubscription = apps.get_model('customers',
                                                'CustomerMarketSubscription')

    # Previous migration made sure this gets everyone we want
    customers = (
        Customer.objects.exclude(market_subscription_1=None)
        .values_list('pk', 'market_subscription_1',
                     'market_subscription_1_backup',
                     'market_subscription_2',
                     'market_subscription_2_backup')
    )

    # This will be ~500,000 objects, so batching...
    for group in grouper(customers.iterator(), n=500):
        new_subscriptions = []
        for customer in group:
            # Missing foreign keys will be None
            try:
                cus_pk, sub_1, sub_1_backup, sub_2, sub_2_backup = customer
            except TypeError:
                # grouper pads the last partial batch with None values
                continue

            new_sub_1 = CustomerMarketSubscription()
            new_sub_1.customer_id = cus_pk
            new_sub_1.market_id = sub_1
            if sub_1_backup:
                new_sub_1.backup_id = sub_1_backup
            new_subscriptions.append(new_sub_1)

            # Check the subscription is not a duplicate
            if sub_2 and sub_2 != sub_1:
                new_sub_2 = CustomerMarketSubscription()
                new_sub_2.customer_id = cus_pk
                new_sub_2.market_id = sub_2
                if sub_2_backup:
                    new_sub_2.backup_id = sub_2_backup
                new_subscriptions.append(new_sub_2)

        CustomerMarketSubscription.objects.bulk_create(new_subscriptions)


def clean_m2m(apps, schema_editor):
    CustomerMarketSubscription = apps.get_model('customers',
                                                'CustomerMarketSubscription')
    CustomerMarketSubscription.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0050_unique_together_customer_markets'),
    ]

    operations = [
        migrations.RunPython(move_to_m2m, clean_m2m),
    ]
