# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 13:29


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0047_clean_gender_data'),
        ('customers', '0051_move_subscriptions_to_m2m'),
    ]

    operations = [
    ]
