# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 10:26


from django.db import migrations


def correct_inconsistent_language_data(apps, schema_editor):
    """
    Update Customers with preferred_language == 'K' to preferred_language ==
    Customer.KISWAHILI.
    Note: Customer.KISWAHILI is not in scope when using apps.get_model so we
    hardcode 'k'.
    """
    Customer = apps.get_model('customers', 'Customer')
    Customer.objects.filter(
        preferred_language='K'
    ).update(preferred_language='k')


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0052_merge'),
    ]

    operations = [
        migrations.RunPython(correct_inconsistent_language_data,
                             reverse_code=migrations.RunPython.noop)
    ]
