# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 13:26


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0053_correct_inconsistent_language_data_20160826_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermarketsubscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_subscriptions', to='customers.Customer'),
        ),
    ]
