# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 16:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0054_auto_20160907_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment',
        ),
    ]
