# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 07:31


import datetime
from django.db import migrations, models
import django.db.models.deletion

from core.utils.datetime import _one_year_from_today


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0055_remove_subscription_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-end_date',)},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=_one_year_from_today),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subscription',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.SubscriptionSource'),
        ),
    ]
