# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 10:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0056_auto_20160909_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditysubscription',
            name='send_tips',
            field=models.BooleanField(default=True, help_text='Send tips for this subscription'),
        ),
        migrations.AlterField(
            model_name='commoditysubscription',
            name='send_market_prices',
            field=models.BooleanField(default=True, help_text='Send market prices for this subscription'),
        ),
    ]
