# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 14:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0057_auto_20160909_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditysubscription',
            name='epoch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='commodity_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', through='customers.CommoditySubscription', to='agri.Commodity', verbose_name='commodity subscriptions'),
        ),
    ]
