# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 12:08


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0058_auto_20160912_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermarketsubscription',
            options={'verbose_name': 'Market subscription'},
        ),
    ]
