# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 07:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0058_auto_20160912_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermarketsubscription',
            options={'verbose_name': 'Market subscription'},
        ),
        migrations.AlterField(
            model_name='commoditysubscription',
            name='epoch_date',
            field=models.DateField(blank=True, help_text='This commodity is event based, and requires a start date', null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='commoditysubscription',
            name='send_market_prices',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commoditysubscription',
            name='send_tips',
            field=models.BooleanField(default=True),
        ),
    ]
