# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 14:57


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0059_auto_20160919_1308'),
        ('customers', '0059_auto_20160916_0815'),
    ]

    operations = [
    ]
