# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 16:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0060_merge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionSource',
            new_name='SubscriptionType',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='source',
            new_name='type',
        ),
    ]
