# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 16:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0061_auto_20160919_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='market_allowance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='price_allowance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='tip_allowance',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
