# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 17:10


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0062_auto_20160919_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='market_allowance',
            new_name='markets_allowance',
        ),
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='price_allowance',
            new_name='prices_allowance',
        ),
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='tip_allowance',
            new_name='tips_allowance',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.Customer', verbose_name='customer'),
        ),
    ]
