# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 10:27


import customers.models
from django.db import migrations, models
from core.utils.datetime import _one_year_from_today


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0063_auto_20160919_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text='Should subscriptions of this type ever expire?'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=_one_year_from_today, help_text='Note that the subscription period is inclusive of the end date'),
        ),
    ]
