# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 13:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0064_auto_20160923_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoditysubscription',
            old_name='send_tips',
            new_name='send_agri_tips',
        ),
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='tips_allowance',
            new_name='agri_tips_allowance',
        ),
    ]
