# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 11:13


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_add_counties'),
        ('customers', '0066_add_free_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.County'),
        ),
    ]
