# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 12:52


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0068_populate_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='world.County'),
        ),
    ]
