# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 14:13


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0069_auto_20161014_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='world.County'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
