# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 09:53


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0071_auto_20161121_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='market_subscription_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='market_subscription_1_backup',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='market_subscription_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='market_subscription_2_backup',
        ),
    ]
