# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-23 13:00


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0072_auto_20170123_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Customer banks',
            },
        ),
        migrations.CreateModel(
            name='CustomerCoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Customer farming cooperatives',
            },
        ),
        migrations.CreateModel(
            name='CustomerSavingsCoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Customer savings cooperatives',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='customer',
            name='farmer_group',
            field=models.CharField(blank=True, max_length=255, verbose_name='Farmer group'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_bank',
            field=models.NullBooleanField(help_text='Does the farmer have an account with a bank', verbose_name='Member of a bank'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_cooperative',
            field=models.NullBooleanField(help_text='Does the farmer sell their produce through a cooperative', verbose_name='Member of a farming cooperative'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_farmer_group',
            field=models.NullBooleanField(help_text='Does the farmer belong to a group of farmers', verbose_name='Member of a farmer group'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_savings_coop',
            field=models.NullBooleanField(help_text='Does the farmer have an account with a savings cooperative', verbose_name='Member of a savings cooperative'),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='National ID number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[(b'm', b'Married'), (b's', b'Single')], max_length=255, verbose_name='Relationship status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank',
            field=models.ForeignKey(blank=True, help_text="Name of the farmer's bank", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.CustomerBank', verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cooperative',
            field=models.ForeignKey(blank=True, help_text="Name of the farmer's farming cooperative", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.CustomerCoop', verbose_name='Cooperative'),
        ),
        migrations.AddField(
            model_name='customer',
            name='savings_coop',
            field=models.ForeignKey(blank=True, help_text="Name of the farmer's savings cooperative", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.CustomerSavingsCoop', verbose_name='Savings cooperative'),
        ),
    ]
