# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 14:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0073_auto_20170123_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercoop',
            name='activity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='customercoop',
            name='town',
            field=models.CharField(blank=True, max_length=255, verbose_name='Town'),
        ),
        migrations.AlterField(
            model_name='customercoop',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
