# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 16:37


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0074_auto_20170124_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('allowance', models.PositiveIntegerField(default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='customers.SubscriptionType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
