# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 16:38


from django.db import migrations


def create_allowances(apps, schema_editor):
    SubscriptionAllowance = apps.get_model('customers', 'SubscriptionAllowance')
    SubscriptionType = apps.get_model('customers', 'SubscriptionType')

    for sub_type in SubscriptionType.objects.all():

        SubscriptionAllowance.objects.create(
            code='markets',
            allowance=sub_type.markets_allowance,
            type=sub_type,
        )

        SubscriptionAllowance.objects.create(
            code='tips',
            allowance=sub_type.agri_tips_allowance,
            type=sub_type,
        )

        SubscriptionAllowance.objects.create(
            code='prices',
            allowance=sub_type.prices_allowance,
            type=sub_type,
        )


def cleanup_allowances(apps, schema_editor):
    SubscriptionAllowance = apps.get_model('customers', 'SubscriptionAllowance')
    SubscriptionAllowance.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0075_auto_20170323_1937'),
    ]

    operations = [
        migrations.RunPython(create_allowances, cleanup_allowances)
    ]
