# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-30 12:42


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0076_transfer_allowances'),
    ]

    database_operations = [
        migrations.AlterModelTable('Task', 'tasks_task'),
        migrations.AlterModelTable('TaskUpdate', 'tasks_taskupdate')
    ]

    state_operations = [
        migrations.DeleteModel('Task'),
        migrations.DeleteModel('TaskUpdate')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
