# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-30 11:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0076_transfer_allowances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditysubscription',
            name='send_agri_tips',
            field=models.BooleanField(default=False),
        ),
    ]
