# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:20


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0077_auto_20170330_1403'),
        ('customers', '0077_auto_20170330_1542'),
    ]

    operations = [
    ]
