# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 14:48


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0078_merge_20170412_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
