# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 14:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0080_customerquestion_customerquestionchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquestionchoice',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=0),
            preserve_default=False,
        ),
    ]
