# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 14:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0081_customerquestionchoice_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerquestionchoice',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='customerquestionchoice',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
