# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 15:02


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0082_auto_20170509_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='customers.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customerquestion',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='customerquestionchoice',
            options={'ordering': ['order'], 'verbose_name': 'Choice'},
        ),
        migrations.RemoveField(
            model_name='customerquestion',
            name='slug',
        ),
        migrations.AddField(
            model_name='customerquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerquestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='customers.CustomerQuestion'),
        ),
    ]
