# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 11:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0084_auto_20170509_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquestion',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
