# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 16:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0085_auto_20170510_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerquestion',
            options={'ordering': ['order'], 'verbose_name': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='customerquestionanswer',
            options={'ordering': ['question__order'], 'verbose_name': 'Answer'},
        ),
        migrations.AlterField(
            model_name='customerquestionanswer',
            name='text',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Answer'),
        ),
        migrations.AlterUniqueTogether(
            name='customerquestionanswer',
            unique_together=set([('customer', 'question')]),
        ),
    ]
