# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 13:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0086_auto_20170511_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquestion',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerquestionchoice',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionallowance',
            name='allowance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
