# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 10:09


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0087_auto_20170515_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='commodities',
            field=models.ManyToManyField(blank=True, related_name='farmers', to='agri.Commodity', verbose_name='commodities farmed'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.Region', verbose_name='agricultural region'),
        ),
    ]
