# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 14:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0088_auto_20170619_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='postal_address',
            field=models.TextField(blank=True, verbose_name='Postal address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Postal code'),
        ),
    ]
