# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 14:10

from collections import defaultdict

from django.db import migrations


def move_address_data_to_fields(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    CQA = apps.get_model('customers', 'CustomerQuestionAnswer')

    addresses = (CQA.objects.filter(question__text='Postal Address')
                            .exclude(text='')
                            .values_list('customer_id', 'text'))
    codes = (CQA.objects.filter(question__text='Postal Code')
                        .exclude(text='')
                        .values_list('customer_id', 'text'))

    customers = defaultdict(dict)

    for address in addresses:
        customer_id, answer = address
        customers[customer_id]['postal_address'] = answer

    for code in codes:
        customer_id, answer = code
        customers[customer_id]['postal_code'] = answer

    for customer_id, answers in customers.items():
        Customer.objects.filter(pk=customer_id).update(**answers)


def cleanup_new_fields(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer.objects.update(postal_address='', postal_code='')


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0089_auto_20171110_1708'),
    ]

    operations = [
        migrations.RunPython(move_address_data_to_fields, cleanup_new_fields)
    ]
