# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 15:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0090_address_answers_into_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='end_message',
            field=models.TextField(blank=True, default='', help_text='Message to send when subscription expires.'),
        ),
    ]
