# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 15:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0091_subscriptiontype_end_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
