# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 16:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0092_subscription_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='is_permanent',
            field=models.BooleanField(db_index=True, default=False, help_text='Should subscriptions of this type ever expire?'),
        ),
    ]
