# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-19 13:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0093_auto_20171220_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='digifarm_farmer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
