# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-26 10:16


from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0094_customer_digifarm_farmer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='africas_talking_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
