# Generated by Django 2.2.7 on 2019-11-26 10:19

import customers.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0095_customer_africas_talking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditysubscription',
            name='commodity',
            field=models.ForeignKey(limit_choices_to=customers.models._limit_subscription_commodity_choices, on_delete=django.db.models.deletion.CASCADE, to='agri.Commodity', verbose_name='commodity'),
        ),
        migrations.AlterField(
            model_name='commoditysubscription',
            name='ended',
            field=models.BooleanField(default=False, help_text='In the case of a moveable-feast subscription, indicates that the customer has come to the end of the agri-tip stream, and is receiving tips from the fallback commodity.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.ForeignKey(blank=True, help_text="Name of the farmer's bank", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customers.CustomerBank', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cooperative',
            field=models.ForeignKey(blank=True, help_text="Name of the farmer's farming cooperative", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.CustomerCoop', verbose_name='Cooperative'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='world.County'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='farm_size',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.00'), 'x&nbsp;&lt;&nbsp;0.25'), (Decimal('0.25'), '0.25&nbsp;&le;&nbsp;x&nbsp;&lt;&nbsp;0.5'), (Decimal('0.50'), '0.5&nbsp;&le;&nbsp;x&nbsp;&lt;&nbsp;0.75'), (Decimal('0.75'), '0.75&nbsp;&le;&nbsp;x&nbsp;&lt;&nbsp;1'), (Decimal('1.00'), '1&nbsp;&le;&nbsp;x&nbsp;&lt;&nbsp;1.5'), (Decimal('1.50'), '1.5&nbsp;&le;&nbsp;x&nbsp;&lt;&nbsp;2'), (Decimal('2.00'), '2&nbsp;&le;&nbsp;x&nbsp;&lt;&nbsp;3'), (Decimal('3.00'), '3&nbsp;&le;&nbsp;x&nbsp;&lt;&nbsp;5'), (Decimal('5.00'), '5&nbsp;&le;&nbsp;x&nbsp;&lt;&nbsp;10'), (Decimal('10.00'), 'x&nbsp;&ge;&nbsp;10')], decimal_places=2, max_digits=4, null=True, verbose_name='size of farm (acres)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='heard_about_us',
            field=models.CharField(blank=True, choices=[('tv', 'SSU TV'), ('rd', 'SSU Radio'), ('fr', 'Friend'), ('ot', 'Other'), ('ss', 'Shamba Shape Up'), ('is', 'Ishamba Web'), ('bm', 'Budget Mkononi Web')], max_length=50, verbose_name='how the customer heard about us'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Permanent notes about this customer not related to a one-off issue.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('s', 'Smartphone'), ('b', 'Basic phone'), ('f', 'Feature phone')], max_length=50, verbose_name='phone type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(choices=[('e', 'English'), ('k', 'Kiswahili')], default='e', max_length=100, verbose_name='preferred language'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agri.Region', verbose_name='agricultural region'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('m', 'Married'), ('s', 'Single')], max_length=255, verbose_name='Relationship status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='savings_coop',
            field=models.ForeignKey(blank=True, help_text="Name of the farmer's savings cooperative", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.CustomerSavingsCoop', verbose_name='Savings cooperative'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male')], max_length=8, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='customerquestionanswer',
            name='text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Answer'),
        ),
    ]
