# Generated by Django 2.2.16 on 2020-10-28 14:12

from django.db import migrations, models

from core.utils.datetime import _get_current_date


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0096_auto_20191126_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(db_index=True, default=_get_current_date),
        ),
    ]
