# Generated by Django 2.2.16 on 2020-11-14 21:03
import logging
from decimal import Decimal
from django.db import migrations, models


LOGGER = logging.getLogger(__name__)


def conform_farm_size(apps, schema_editor):
    customer_model = apps.get_model('customers', 'Customer')

    for low, high, value in [
        (0, 1, 0.50),
        (1, 2.5, 1.50),
        (2.5, 5.5, 4.00),
        (5.5, 10.5, 8.00),
        (10.5, 20, 15.00),
        (20, None, 30.00)
    ]:
        qs = customer_model.objects.filter(farm_size__gte=low)
        if high:
            qs = qs.filter(farm_size__lt=high)
        qs.update(farm_size=value)


def undo_conform_farm_size(apps, schema_editor):
    LOGGER.critical("Migration is undone, but farm size data can not be restored back.")


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0097_auto_20201028_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='farm_size',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.50'), 'Less than 1'), (Decimal('1.50'), '1&ndash;2'), (Decimal('4.00'), '3&ndash;5'), (Decimal('8.00'), '6&ndash;10'), (Decimal('15.00'), '11&ndash;20'), (Decimal('30.00'), 'More than 20')], decimal_places=2, max_digits=4, null=True, verbose_name='size of farm (acres)'),
        ),
        migrations.RunPython(conform_farm_size, reverse_code=undo_conform_farm_size)
    ]

