# Generated by Django 2.2.17 on 2021-01-27 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0023_auto_20191126_1319'),
        ('customers', '0098_auto_20201115_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('date_planted', models.DateField()),
                ('used_certified_seed', models.BooleanField(blank=True, null=True)),
                ('acres_planted', models.FloatField(blank=True, null=True)),
                ('cost_of_seeds', models.FloatField(blank=True, null=True)),
                ('cost_of_fertilizer', models.FloatField(blank=True, null=True)),
                ('cost_currency', models.CharField(blank=True, choices=[('kes', 'Kenya shillings'), ('gbp', 'Pound sterling'), ('ugx', 'Uganda shillings'), ('usd', 'US dollars')], max_length=16, null=True)),
                ('harvest_amount', models.FloatField(blank=True, null=True)),
                ('harvest_units', models.CharField(blank=True, choices=[('kgs', 'kgs'), ('items', 'items'), ('50kgbag', '50 kg bags'), ('90kgbag', '90 kg bags'), ('100kgbag', '100 kg bags')], max_length=16, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri.Commodity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
            options={
                'verbose_name': 'Crop history',
                'verbose_name_plural': 'Crop histories',
            },
        ),
    ]
