# Generated by Django 2.2.19 on 2021-03-08 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0099_crophistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMiscData',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='misc_data', serialize=False, to='customers.Customer')),
                ('school_name_raw', models.CharField(blank=True, max_length=100)),
                ('county_name_raw', models.CharField(blank=True, max_length=20)),
                ('livestock_raw', models.CharField(blank=True, max_length=100)),
                ('livestock_unmatched', models.IntegerField(blank=True, null=True)),
                ('crops_raw', models.CharField(blank=True, max_length=100)),
                ('crops_unmatched', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
