# Generated by Django 3.2.10 on 2021-12-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0100_customermiscdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='has_bank',
            field=models.BooleanField(blank=True, help_text='Does the farmer have an account with a bank', null=True, verbose_name='Member of a bank'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='has_cooperative',
            field=models.BooleanField(blank=True, help_text='Does the farmer sell their produce through a cooperative', null=True, verbose_name='Member of a farming cooperative'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='has_farmer_group',
            field=models.BooleanField(blank=True, help_text='Does the farmer belong to a group of farmers', null=True, verbose_name='Member of a farmer group'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='has_savings_coop',
            field=models.BooleanField(blank=True, help_text='Does the farmer have an account with a savings cooperative', null=True, verbose_name='Member of a savings cooperative'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
