# Generated by Django 2.2.24 on 2021-12-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0103_remap_border_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='old_address_county',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='old_county',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='old_sub_county',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='old_ward',
        ),
    ]
