# Generated by Django 3.2.11 on 2022-01-24 13:34

from django.db import migrations, models
from django.contrib.gis.db import models as gis_models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0105_set_ward_from_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='village',
            field=models.CharField(blank=True, max_length=120, verbose_name='village'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=gis_models.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
