# Generated by Django 3.2.12 on 2022-03-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0106_alter_customer_fields_optionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='join_method',
            field=models.CharField(blank=True, choices=[('blacklist', 'Blacklist'), ('call', 'Call'), ('digifarm', 'Digifarm'), ('import', 'Import'), ('invalid', 'Invalid'), ('sms', 'Sms'), ('staff', 'Staff'), ('?', 'Unknown'), ('ussd', 'Ussd'), ('web', 'Web')], default='?', max_length=20, verbose_name='how this customer joined'),
        ),
        migrations.AddField(
            model_name='customer',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='when this customer requested stop'),
        ),
        migrations.AddField(
            model_name='customer',
            name='stop_method',
            field=models.CharField(blank=True, choices=[('blacklist', 'Blacklist'), ('call', 'Call'), ('digifarm', 'Digifarm'), ('import', 'Import'), ('invalid', 'Invalid'), ('sms', 'Sms'), ('staff', 'Staff'), ('?', 'Unknown'), ('ussd', 'Ussd'), ('web', 'Web')], default='?', max_length=20, verbose_name='how this customer requested stop'),
        ),
    ]
