# Generated by Django 3.2.12 on 2022-04-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0107_join_stop_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(choices=[(None, '(Unknown)'), ('bnt', 'Bantu'), ('bem', 'Bemba'), ('eng', 'English'), ('swa', 'Kiswahili'), ('loz', 'Lozi'), ('lug', 'Luganda'), ('nya', 'Nyanja'), ('toi', 'Tonga')], default='eng', max_length=3, verbose_name='preferred language'),
        ),
    ]
