# Generated by Django 3.2.12 on 2022-04-15 12:52

from django.db import migrations, models
from django.conf import settings

import logging
logger = logging.getLogger(__name__)

mappings = {
    'e': 'eng',  # English
    'k': 'swa',  # Kiswahili
}


def update_language_codes(apps, schema_editor):
    db = settings.DATABASES['default']
    db_name = db.get('NAME')
    db_schema = db.get('SCHEMA')
    db_alias = schema_editor.connection.alias

    logger.setLevel(logging.INFO)
    settings.LOGGING['loggers']['django'] = {'level': 'INFO', 'handlers': ['console']}

    Customer = apps.get_model("customers", "Customer")  # NOQA

    old_lang_codes = Customer.objects.using(db_alias).order_by('preferred_language').distinct('preferred_language').values_list('preferred_language', flat=True)

    for old_code in old_lang_codes:
        new_code = mappings[old_code]  # Throw an exception if it's a lang that we don't know about
        Customer.objects.filter(preferred_language=old_code).update(preferred_language=new_code)


def restore_language_codes(apps, schema_editor):
    db = settings.DATABASES['default']
    db_name = db.get('NAME')
    db_schema = db.get('SCHEMA')
    db_alias = schema_editor.connection.alias

    logger.setLevel(logging.INFO)
    settings.LOGGING['loggers']['django'] = {'level': 'INFO', 'handlers': ['console']}

    Customer = apps.get_model("customers", "Customer")  # NOQA

    inv_map = {v: k for k, v in mappings.items()}

    old_lang_codes = Customer.objects.using(db_alias).order_by('preferred_language').distinct('preferred_language').values_list('preferred_language', flat=True)

    for old_code in old_lang_codes:
        new_code = inv_map[old_code]  # Throw an exception if it's a lang that we don't know about
        Customer.objects.filter(preferred_language=old_code).update(preferred_language=new_code)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0108_alter_customer_preferred_language'),
    ]

    operations = [
        migrations.RunPython(update_language_codes, restore_language_codes),
    ]

