# Generated by Django 3.2.13 on 2022-04-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_remove_world_county_data'),
        ('customers', '0109_migrate_customer_preferred_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='country',
            new_name='border0',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='county',
            new_name='border1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='subcounty',
            new_name='border2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ward',
            new_name='border3',
        ),

        migrations.AlterField(
            model_name='customer',
            name='border0',
            field=models.ForeignKey(blank=True, null=True, limit_choices_to={'level': 0}, on_delete=django.db.models.deletion.SET_NULL, related_name='border0_of', to='world.border'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='border1',
            field=models.ForeignKey(blank=True, null=True, limit_choices_to={'level': 1}, on_delete=django.db.models.deletion.SET_NULL, related_name='border1_of', to='world.border'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='border2',
            field=models.ForeignKey(blank=True, null=True, limit_choices_to={'level': 2}, on_delete=django.db.models.deletion.SET_NULL, related_name='border2_of', to='world.border'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='border3',
            field=models.ForeignKey(blank=True, null=True, limit_choices_to={'level': 3}, on_delete=django.db.models.deletion.SET_NULL, related_name='border3_of', to='world.border'),
        ),
    ]
