# Generated by Django 3.2.14 on 2022-08-23 22:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0110_i18n_administrative_borders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('is_main', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='phones',
                                               to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer phone number',
                'verbose_name_plural': 'Customer phone numbers',
            },
        ),
        migrations.AddConstraint(
            model_name='customerphone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('customer',),
                                               name='unique_customer_main_number'),
        ),
        migrations.AddIndex(
            model_name='customerphone',
            index=models.Index(fields=['is_main'], name='customers_phone_is_main_idx'),
        ),
    ]
