# Generated by Django 3.2.14 on 2022-08-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0112_customerphone_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='africas_talking_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
