# Generated by Django 3.2.15 on 2022-11-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0114_let_it_rain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_method',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('digifarm', 'Digifarm'), ('import', 'Import'), ('sms', 'SMS'), ('staff', 'Staff'), ('?', 'Unknown'), ('ussd', 'USSD'), ('web', 'Web')], default='?', max_length=20, verbose_name='how this customer joined'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stop_method',
            field=models.CharField(blank=True, choices=[('blacklist', 'Blacklist'), ('call', 'Call'), ('import', 'Import'), ('invalid', 'Invalid'), ('sms', 'SMS'), ('staff', 'Staff'), ('?', 'Unknown')], default='?', max_length=20, verbose_name='how this customer stopped'),
        ),
    ]
