# Generated by Django 3.2.15 on 2022-11-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0115_split_stop_join_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('raw_input', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_responses', to='customers.customer')),
            ],
            options={
                'verbose_name': 'NPS Response',
                'verbose_name_plural': 'NPS Responses',
            },
        ),
        migrations.AddIndex(
            model_name='npsresponse',
            index=models.Index(fields=['score'], name='nps_response_score_idx'),
        ),
        migrations.AddIndex(
            model_name='npsresponse',
            index=models.Index(fields=['created'], name='nps_response_created_idx'),
        ),
    ]
