# Generated by Django 4.1.6 on 2023-02-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0034_marketsubscription_data"),
        ("customers", "0116_nps_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="markets",
            field=models.ManyToManyField(
                through="markets.MarketSubscription", to="markets.market"
            ),
        ),
        migrations.DeleteModel(
            name="CustomerMarketSubscription",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="commodity_subscriptions",
        ),
        migrations.AlterField(
            model_name="customer",
            name="commodities",
            field=models.ManyToManyField(
                blank=True,
                related_name="customers",
                to="agri.commodity",
                verbose_name="commodities farmed",
            ),
        ),
    ]
