# Generated by Django 4.1.7 on 2023-02-21 20:33

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0117_remove_customermarketsubscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customercategory",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "verbose_name_plural": "Customer categories",
            },
        ),
    ]
