# Generated by Django 4.1.8 on 2023-05-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0118_alter_customercategory_sorting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"permissions": [("export", "Can export tasks")]},
        ),
    ]
