# Generated by Django 4.1.9 on 2023-06-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0119_add_export_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="join_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bm-chatbot", "Bm_Chatbot"),
                    ("call", "Call"),
                    ("digifarm", "Digifarm"),
                    ("import", "Import"),
                    ("sms", "SMS"),
                    ("staff", "Staff"),
                    ("?", "Unknown"),
                    ("ussd", "USSD"),
                    ("web", "Web"),
                ],
                default="?",
                max_length=20,
                verbose_name="how this customer joined",
            ),
        ),
    ]
