# Generated by Django 4.1.9 on 2023-09-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0120_alter_customer_join_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerphone',
            name='gdpr_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
