# Generated by Django 4.1.10 on 2023-11-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0123_remove_subscriptionallowance_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number_hash'], name='phone_number_hash_idx'),
        ),
    ]
