# Generated by Django 4.1.12 on 2023-10-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0011_remove_world_county_data"),
        ("customers", "0124_customer_phone_number_hash_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSurvey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("creator_id", models.IntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("last_editor_id", models.IntegerField(blank=True, null=True)),
                ("survey_start", models.DateField(auto_now_add=True)),
                ("survey_title", models.CharField(max_length=255)),
                (
                    "data_source",
                    models.CharField(
                        choices=[(None, "Unknown"), ("ussd", "USSD"), ("web", "Web")],
                        default="ussd",
                        max_length=8,
                        verbose_name="data source",
                    ),
                ),
                ("responses", models.JSONField()),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_data",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
