# Generated by Django 4.1.9 on 2024-02-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0125_add_customersurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='farm_size',
            field=models.CharField(blank=True, choices=[('0.50', 'Less than 1'), ('1.50', '1-2'), ('4.00', '3-5'), ('8.00', '6-10'), ('15.00', '11-20'), ('30.00', 'More than 20')], max_length=50, null=True, verbose_name='size of farm (acres)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='join_method',
            field=models.CharField(blank=True, choices=[('bm-chatbot', 'budgetmkononi chatbot'), ('call', 'call to center'), ('digifarm', 'digifarm'), ('import', 'bulk import'), ('sms', 'sms keyword'), ('staff', 'staff created'), ('?', 'unknown'), ('ussd', 'ussd session'), ('web', 'ishamba.com')], default='?', max_length=20, verbose_name='how this customer joined'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stop_method',
            field=models.CharField(blank=True, choices=[('blacklist', 'MNO blacklist'), ('call', 'call to center'), ('import', 'bulk import'), ('invalid', 'invalid number'), ('sms', 'sms keyword'), ('staff', 'staff created'), ('?', 'unknown')], default='?', max_length=20, verbose_name='how this customer stopped'),
        ),
    ]
