# Generated by Django 4.1.9 on 2024-03-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0128_customercommodity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='commodities',
        ),
    ]
