# Generated by Django 4.1.9 on 2024-03-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0025_delete_agritipsentsms'),
        ('customers', '0129_remove_customer_commodities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='commodities',
            field=models.ManyToManyField(blank=True, related_name='customers', through='customers.CustomerCommodity', to='agri.commodity', verbose_name='commodities farmed'),
        ),
    ]
