# Generated by Django 4.1.13 on 2024-05-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0130_customer_commodities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercommodity',
            name='subscription_flag',
            field=models.CharField(blank=True, choices=[(None, 'No subscription flags'), ('premium', 'Premium'), ('freemium', 'Freemium')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='farm_size',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('0.50', 'Less than 1'), ('1.50', '1-2'), ('4.00', '3-5'), ('8.00', '6-10'), ('15.00', '11-20'), ('30.00', 'More than 20'), ('', 'Unspecified')], max_length=50, null=True, verbose_name='size of farm (acres)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='heard_about_us',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('fr', 'Friend'), ('ot', 'Other'), ('ss', 'Shamba Shape Up'), ('is', 'Ishamba Web'), ('bm', 'Budget Mkononi Web')], max_length=50, verbose_name='how the customer heard about us'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='join_method',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('bm-chatbot', 'budgetmkononi chatbot'), ('call', 'call to center'), ('digifarm', 'digifarm'), ('import', 'bulk import'), ('sms', 'sms keyword'), ('staff', 'staff created'), ('?', 'unknown'), ('ussd', 'ussd session'), ('web', 'ishamba.com'), ('', 'Unspecified')], default='?', max_length=20, verbose_name='how this customer joined'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_type',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('s', 'Smartphone'), ('b', 'Basic phone'), ('f', 'Feature phone'), ('', 'Unspecified')], max_length=50, verbose_name='phone type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('m', 'Married'), ('s', 'Single'), ('', 'Unspecified')], max_length=255, verbose_name='Relationship status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('f', 'Female'), ('m', 'Male'), ('', 'Unspecified')], max_length=8, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stop_method',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('blacklist', 'MNO blacklist'), ('call', 'call to center'), ('import', 'bulk import'), ('invalid', 'invalid number'), ('sms', 'sms keyword'), ('staff', 'staff created'), ('?', 'unknown')], default='?', max_length=20, verbose_name='how this customer stopped'),
        ),
    ]
