# Generated by Django 4.1.13 on 2024-05-06 08:17
from django.db import migrations

from agri.constants import SUBSCRIPTION_FLAG


def populate_freemium_customer_commodities(apps, schema_editor):
    CustomerCommodity = apps.get_model('customers', 'customercommodity')
    CustomerCommodity.objects.filter(primary=True).update(subscription_flag=SUBSCRIPTION_FLAG.FREEMIUM)


def migrate_tip_subscriptions_to_customer_commodities(apps, schema_editor):
    CustomerCommodity = apps.get_model('customers', 'customercommodity')
    TipSeriesSubscription = apps.get_model('tips', 'tipseriessubscription')
    for tip_sub in TipSeriesSubscription.objects.filter(ended=False):
        customer = tip_sub.customer
        current_sub = customer.current_subscription
        if current_sub and current_sub.is_premium:
            CustomerCommodity.objects.update_or_create(
                commodity_id=tip_sub.series.commodity_id,
                customer=customer,
                defaults={'subscription_flag': SUBSCRIPTION_FLAG.PREMIUM},
            )
        else:
            CustomerCommodity.objects.update_or_create(
                commodity_id=tip_sub.series.commodity_id,
                customer=customer,
                defaults={'subscription_flag': SUBSCRIPTION_FLAG.FREEMIUM},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0131_customercommodity_subscription_flag_and_more'),
        ('tips', '0037_auto_20240430_1022'),
    ]

    operations = [
        migrations.RunPython(populate_freemium_customer_commodities, migrations.RunPython.noop),
        migrations.RunPython(migrate_tip_subscriptions_to_customer_commodities, migrations.RunPython.noop),
    ]
