# Generated by Django 4.1.13 on 2024-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0132_auto_20240506_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersurvey',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='survey_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
