# Generated by Django 4.1.13 on 2024-07-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0133_remove_customersurvey_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('bnt', 'Bantu'), ('bem', 'Bemba'), ('eng', 'English'), ('swa', 'Kiswahili'), ('loz', 'Lozi'), ('lug', 'Luganda'), ('nya', 'Nyanja'), ('toi', 'Tonga')], max_length=10, null=True),
        ),
    ]
