# Generated by Django 4.1.13 on 2024-09-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0134_customersurvey_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='skip_ai_invocation',
            field=models.BooleanField(default=False, verbose_name='do not invoke ai for this customer'),
        ),
    ]
