# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-30 12:44


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customers', '0077_auto_20170330_1542'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[(b'new', b'New'), (b'in progress', b'In progress'), (b'resolved', b'Resolved'), (b'unresolved', b'Unresolved')], default=b'new', max_length=100, verbose_name='status')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='customers.Customer', verbose_name='customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Markdown formatting is supported.', verbose_name='message')),
                ('update_type', models.CharField(blank=True, choices=[(b'cannot-contact', b'Cannot contact customer')], max_length=50, null=True)),
                ('status', models.CharField(choices=[(b'new', b'New'), (b'in progress', b'In progress'), (b'resolved', b'Resolved'), (b'unresolved', b'Unresolved')], max_length=100, verbose_name='status')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
