# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-04 08:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('unresolved', 'Unresolved')], default='new', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('unresolved', 'Unresolved')], max_length=100, verbose_name='status'),
        ),
    ]
