# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-04 08:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170404_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16, verbose_name='Priority'),
            preserve_default=False,
        ),
    ]
