# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-05 05:57


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.MCRM_SMS_INCOMINGSMS_MODEL),
        ('sms', '0028_bespokesentsms_sent_by'),
        ('tasks', '0005_task_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='incoming_messages',
            field=models.ManyToManyField(to=settings.MCRM_SMS_INCOMINGSMS_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='outgoing_messages',
            field=models.ManyToManyField(to='sms.BespokeSentSMS'),
        ),
    ]
