# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 14:46


from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20170405_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='outgoing_messages',
            field=models.ManyToManyField(blank=True, to='sms.BespokeSentSMS'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
