# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 14:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20170415_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contact_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
