# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 17:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_contact_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contact_attempts',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
