# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 18:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20170424_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
