# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 10:09


from django.db import migrations
from taggit.managers import TaggableManager


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20170613_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
