# Generated by Django 2.2.7 on 2019-11-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20170619_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='update_type',
            field=models.CharField(blank=True, choices=[('cannot-contact', 'Cannot contact customer')], max_length=50, null=True),
        ),
    ]
