# Generated by Django 2.2.19 on 2021-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20191126_1319'),
    ]

    operations = [
        # Change the status level names for clarity
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('progressing', 'Progressing'), ('closed_resolved', 'Closed:Resolved'), ('closed_unresolved', 'Closed:Unresolved')], default='new', max_length=100, verbose_name='status'),
        ),
        # Change the status level names for clarity
        migrations.AlterField(
            model_name='taskupdate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('progressing', 'Progressing'), ('closed_resolved', 'Closed:Resolved'), ('closed_unresolved', 'Closed:Unresolved')], max_length=100, verbose_name='status'),
        ),
        # Set the default priority to medium
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16, verbose_name='Priority'),
        ),
    ]
