# Generated by Django 2.2.19 on 2021-06-28 19:26

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Task = apps.get_model("tasks", "Task")
    db_alias = schema_editor.connection.alias
    progressing_count = Task.objects.using(db_alias).filter(status="in_progress").update(status="progressing")
    resolved_count = Task.objects.using(db_alias).filter(status="resolved").update(status="closed_resolved")
    unresolved_count = Task.objects.using(db_alias).filter(status="unresolved").update(status="closed_unresolved")
    # Set all unspecified Task priorities to a default of 'medium'
    no_priority_count = Task.objects.using(db_alias).filter(priority="").update(priority="medium")


def reverse_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Task = apps.get_model("tasks", "Task")
    db_alias = schema_editor.connection.alias
    progressing_count = Task.objects.using(db_alias).filter(status="progressing").update(status="in_progress")
    resolved_count = Task.objects.using(db_alias).filter(status="closed_resolved").update(status="resolved")
    unresolved_count = Task.objects.using(db_alias).filter(status="closed_unresolved").update(status="unresolved")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_rename_task_status_choices'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
