# Generated by Django 2.2.19 on 2021-06-30 15:54

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    TaskUpdate = apps.get_model("tasks", "TaskUpdate")
    db_alias = schema_editor.connection.alias
    progressing_count = TaskUpdate.objects.using(db_alias).filter(status="in_progress").update(status="progressing")
    resolved_count = TaskUpdate.objects.using(db_alias).filter(status="resolved").update(status="closed_resolved")
    unresolved_count = TaskUpdate.objects.using(db_alias).filter(status="unresolved").update(status="closed_unresolved")


def reverse_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    TaskUpdate = apps.get_model("tasks", "TaskUpdate")
    db_alias = schema_editor.connection.alias
    progressing_count = TaskUpdate.objects.using(db_alias).filter(status="progressing").update(status="in_progress")
    resolved_count = TaskUpdate.objects.using(db_alias).filter(status="closed_resolved").update(status="resolved")
    unresolved_count = TaskUpdate.objects.using(db_alias).filter(status="closed_unresolved").update(status="unresolved")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_migrate_task_status_records'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
