# Generated by Django 2.2.19 on 2021-06-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_migrate_taskupdate_status_records'),
    ]

    operations = [
        # The priority field is now required for every Task (cannot be blank)
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16, verbose_name='Priority'),
        ),
    ]
