# Generated by Django 2.2.24 on 2021-08-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_change_task_priority_constraints'),
        ('sms', '0042_outgoingsms_from_bespokesentsms_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='outgoing_messages',
            field=models.ManyToManyField(blank=True, to='sms.OutgoingSMS'),
        ),
    ]
