# Generated by Django 4.1.8 on 2023-05-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_alter_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"permissions": [("export", "Can export tasks")]},
        ),
    ]
