# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-31 16:16


import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20161020_1029'),
        ('weather', '0008_auto_20160914_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('last_editor_id', models.IntegerField(blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('text', models.CharField(max_length=160)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='world.County')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
