# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-31 16:28


import django.contrib.postgres.fields.ranges
from django.db import migrations
import weather.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_countyforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countyforecast',
            name='dates',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=weather.models._this_month),
        ),
    ]
