# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-31 16:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20170131_1928'),
    ]

    operations = [
        migrations.RunSQL("CREATE INDEX on weather_countyforecast USING GIST (dates)"),
    ]
