# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-01 10:25


import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import weather.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_gist_index_countyforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countyforecast',
            name='dates',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=weather.models._this_month, help_text='Range of dates the forecast covers. Start is inclusive, end is exclusive'),
        ),
    ]
