# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-01 14:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_auto_20170201_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyforecast',
            name='sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
