# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_countyforecast_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastday',
            name='json',
        ),
    ]
