# Generated by Django 2.2.24 on 2021-10-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_remove_forecastday_json'),
    ]

    operations = [
    ]
