# Generated by Django 2.2.24 on 2021-12-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_border_borderlevelname'),
        ('weather', '0015_delete_sentsms_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyforecast',
            name='new_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='world.Border'),
        ),
    ]
