# Generated by Django 2.2.24 on 2021-12-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0017_map_county_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countyforecast',
            name='county',
        ),
        migrations.RenameField(
            model_name='countyforecast',
            old_name='new_county',
            new_name='county',
        ),
        migrations.AlterField(
            model_name='countyforecast',
            name='county',
            # Drop the blank=True, null=True params to force all county weather forecasts to have a county specified
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='world.Border'),
        ),
    ]
