# Generated by Django 4.1.7 on 2023-02-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0118_alter_customercategory_sorting"),
        ("weather", "0018_remove_old_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="countyforecast",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_forecasts",
                to="customers.customercategory",
            ),
        ),
    ]
