# Generated by Django 4.1.7 on 2023-02-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0019_countyforecast_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="countyforecast",
            name="premium_only",
            field=models.BooleanField(default=True),
        ),
    ]
