# Generated by Django 4.1.9 on 2023-10-16 09:33

import core.utils.datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0123_remove_subscriptionallowance_type_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SubscriptionType',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created', models.DateTimeField(auto_now_add=True, null=True)),
                        ('creator_id', models.IntegerField(blank=True, null=True)),
                        ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                        ('last_editor_id', models.IntegerField(blank=True, null=True)),
                        ('name', models.CharField(db_index=True, max_length=255)),
                        ('markets_allowance', models.PositiveIntegerField(blank=True, default=0)),
                        ('agri_tips_allowance', models.PositiveIntegerField(blank=True, default=0)),
                        ('prices_allowance', models.PositiveIntegerField(blank=True, default=0)),
                        ('is_permanent', models.BooleanField(db_index=True, default=False, help_text='Should subscriptions of this type ever expire?')),
                        ('end_message', models.TextField(blank=True, default='', help_text='Message to send when subscription expires.')),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
            ],
            # Table already exists. See customers/migrations/0123_remove_subscriptionallowance_type_and_more.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SubscriptionAllowance',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created', models.DateTimeField(auto_now_add=True, null=True)),
                        ('creator_id', models.IntegerField(blank=True, null=True)),
                        ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                        ('last_editor_id', models.IntegerField(blank=True, null=True)),
                        ('code', models.CharField(db_index=True, max_length=100)),
                        ('allowance', models.PositiveSmallIntegerField(default=0)),
                        ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='subscriptions.subscriptiontype')),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
            ],
            # Table already exists. See customers/migrations/0123_remove_subscriptionallowance_type_and_more.py
            database_operations=[],
        ),

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Subscription',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created', models.DateTimeField(auto_now_add=True, null=True)),
                        ('creator_id', models.IntegerField(blank=True, null=True)),
                        ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                        ('last_editor_id', models.IntegerField(blank=True, null=True)),
                        ('start_date', models.DateField(db_index=True, default=core.utils.datetime._get_current_date)),
                        ('end_date', models.DateField(db_index=True, default=core.utils.datetime._one_year_from_today, help_text='Note that the subscription period is inclusive of the end date')),
                        ('ended', models.BooleanField(db_index=True, default=False)),
                        ('extra', models.JSONField(blank=True, null=True)),
                        ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer', verbose_name='customer')),
                        ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptiontype')),
                    ],
                    options={
                        'ordering': ('-end_date',),
                    },
                ),
            ],
            # Table already exists. See customers/migrations/0123_remove_subscriptionallowance_type_and_more.py
            database_operations=[],
        ),
    ]
