# Generated by Django 4.1.9 on 2023-10-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
