# Generated by Django 4.1.9 on 2023-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_external_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='Should customers pay for this subscription?'),
        ),
    ]
