# Generated by Django 4.1.9 on 2023-09-26 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_remove_world_county_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('analysts', models.ManyToManyField(blank=True, related_name='call_centers', to=settings.AUTH_USER_MODEL)),
                ('border', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='call_center', to='world.border')),
                ('sender_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
