# Generated by Django 4.1.9 on 2023-09-29 09:23

from django.db import migrations


def create_national_call_centers(apps, schema_editor):
    CallCenter = apps.get_model('callcenters', 'callcenter')
    Border = apps.get_model('world', 'border')
    User = apps.get_model('auth', 'user')

    for country in Border.objects.filter(level=0):
        call_center, created = CallCenter.objects.get_or_create(
            border=country,
            defaults={'name': country.name}
        )
        call_center.analysts.set(User.objects.all())

class Migration(migrations.Migration):

    dependencies = [
        ('callcenters', '0001_initial'),
        ('world', '0011_remove_world_county_data'),
    ]

    operations = [
        migrations.RunPython(create_national_call_centers)
    ]
