# Generated by Django 4.1.9 on 2023-10-13 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_analysts(apps, schema_editor):
    CallCenter = apps.get_model('callcenters', 'callcenter')
    CallCenterOperator = apps.get_model('callcenters', 'callcenteroperator')
    analysts = []
    for call_center in CallCenter.objects.all():
        for analyst in call_center.analysts.all():
            analysts.append(
                CallCenterOperator(operator=analyst, call_center=call_center)
            )
    CallCenterOperator.objects.bulk_create(analysts, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callcenters', '0002_auto_20230929_1223'),
        ('world', '0011_remove_world_county_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenterOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='callcenter',
            name='border',
            field=models.OneToOneField(limit_choices_to={'level__in': [0, 1]}, on_delete=django.db.models.deletion.RESTRICT, related_name='call_center', to='world.border'),
        ),
        migrations.AddField(
            model_name='callcenteroperator',
            name='call_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_center_operators', to='callcenters.callcenter'),
        ),
        migrations.AddField(
            model_name='callcenteroperator',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_center_operators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='callcenteroperator',
            unique_together={('call_center', 'operator')},
        ),
        migrations.RunPython(migrate_analysts),
        migrations.RemoveField(
            model_name='callcenter',
            name='analysts',
        ),
    ]
