# Generated by Django 4.1.9 on 2023-11-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenters', '0003_callcenteroperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenterSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='callcenter',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='callcenter',
            name='senders',
            field=models.ManyToManyField(related_name='call_centers', to='callcenters.callcentersender'),
        ),
    ]
