# Generated by Django 4.1.13 on 2024-12-09 14:44

from django.db import migrations


def create_zambia_call_center(apps, schema_editor):
    CallCenter = apps.get_model('callcenters', 'callcenter')
    CallCenterSender = apps.get_model('callcenters', 'callcentersender')
    Border = apps.get_model('world', 'border')

    country = Border.objects.get(name='Zambia', level=0)
    call_center, __ = CallCenter.objects.get_or_create(
        border=country,
        defaults={'name': country.name}
    )

    sender, __ = CallCenterSender.objects.get_or_create(
        sender_id="384",
        description="Shared Short Code for iMunda")
    call_center.senders.add(sender)

class Migration(migrations.Migration):

    dependencies = [
        ('callcenters', '0004_callcentersender_remove_callcenter_sender_id_and_more'),
    ]

    operations = [
        migrations.RunPython(create_zambia_call_center, reverse_code=migrations.RunPython.noop)
    ]
