# Generated by Django 4.1.13 on 2024-12-13 11:38

from django.db import migrations


def add_operators(apps, schema_editor):
    CallCenter = apps.get_model('callcenters', 'callcenter')
    CallCenterOperator = apps.get_model('callcenters', 'callcenteroperator')
    User = apps.get_model('auth', 'user')

    operators = []
    call_center = CallCenter.objects.get(name="Zambia")
    for user in User.objects.all():
        operators.append(
            CallCenterOperator(operator=user, call_center=call_center)
        )
    CallCenterOperator.objects.bulk_create(operators, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('callcenters', '0005_auto_20241209_1744'),
    ]

    operations = [
        migrations.RunPython(add_operators, reverse_code=migrations.RunPython.noop)
    ]
